name: local_ocr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  ## Controller
  equatable: ^2.0.7
  hydrated_bloc: ^10.1.1

  ## Helper
  intl: ^0.20.2
  image: ^4.5.4
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  ## OCR
  flutter_tesseract_ocr: ^0.4.30 
  google_mlkit_text_recognition: ^0.15.0

  ## Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
