name: local_ocr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  ## Controller
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  ## Helper
  path: ^1.9.0
  intl: ^0.20.2
  image: ^4.5.4
  get_it: ^8.0.2
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_overlay_window: ^0.5.0

  ## OCR
  flutter_tesseract_ocr: ^0.4.30 
  google_mlkit_text_recognition: ^0.15.0

  ## Database
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
